# -*- coding: utf-8 -*-
"""LSTM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fJP5kkCAe-rNNbpdowL3NGKND-FrwLCa
"""

from google.colab import drive
drive.mount('/content/drive')

!ls 'drive/My Drive/megathon_pwc'

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Activation
from keras.layers import TimeDistributed
from keras.layers import Reshape
from keras.layers import Flatten
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('/content/drive/My Drive/megathon_pwc/drainage_data_high_large.csv')

df.columns=['Date','Gas','Flow','Level','Temperature','Label']
x = df[['Gas','Flow','Level','Temperature']]
y = df[['Label']]

y_arr = y.to_numpy()
y_arr = np.reshape(y_arr,(y_arr.shape[0],))

y_arr = y_arr - 1
y_data = np.zeros((y_arr.shape[0], 4))
y_data[np.arange(y_arr.shape[0]), y_arr] = 1

x_np = x.to_numpy()
x_np = x_np - x_np.mean()
x_np = x_np/x_np.max()

x_new = np.reshape(x_np,(int(x_np.shape[0]/5),5,x_np.shape[1]))    
y_new = np.reshape(y_data,(int(y_data.shape[0]/5),5,y_data.shape[1]))

X_train, X_validation, y_train, y_validation = train_test_split(
    x_new,
    y_new,
    test_size=0.2,
    random_state=4)

X_validation.shape

model = Sequential()

model.add(LSTM(5,batch_input_shape=(None,5,4),return_sequences=True))
model.add(LSTM(5,batch_input_shape=(None,5,4),return_sequences=True,dropout=0.5))
model.add(LSTM(5,batch_input_shape=(None,5,4),return_sequences=True))
model.add(TimeDistributed(Dense(4,activation='softmax')))

model.summary()

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

# X_train = np.expand_dims(X_train,axis=3)
history = model.fit(X_train,y_train,epochs=1000,validation_data=(X_validation,y_validation))

results = model.predict_classes(X_validation)

results

model.save('/content/drive/My Drive/megathon_pwc/three_layer_high_large_dropout.h5')

